web_scraping_task:
  description: >
    Scrape the web for information about {url}
    Make sure you extract the most relevant information from the website, try to extract the contact us information 
    if the website is a business entity what kind of business they do, how many employees they might have, 
    what location the business is in, and any other relevant information.
  expected_output: >
    Extracted text from the website related to {url}
  agent: web_scraper